// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/adopter/adopter-api-v1.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SetResourceRequest struct {
	Payload              []byte               `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Logs                 []byte               `protobuf:"bytes,2,opt,name=logs,proto3" json:"logs,omitempty"`
	Version              string               `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Algorithm            string               `protobuf:"bytes,4,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SetResourceRequest) Reset()         { *m = SetResourceRequest{} }
func (m *SetResourceRequest) String() string { return proto.CompactTextString(m) }
func (*SetResourceRequest) ProtoMessage()    {}
func (*SetResourceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_383081686ffb1987, []int{0}
}

func (m *SetResourceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetResourceRequest.Unmarshal(m, b)
}
func (m *SetResourceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetResourceRequest.Marshal(b, m, deterministic)
}
func (m *SetResourceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetResourceRequest.Merge(m, src)
}
func (m *SetResourceRequest) XXX_Size() int {
	return xxx_messageInfo_SetResourceRequest.Size(m)
}
func (m *SetResourceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetResourceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetResourceRequest proto.InternalMessageInfo

func (m *SetResourceRequest) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *SetResourceRequest) GetLogs() []byte {
	if m != nil {
		return m.Logs
	}
	return nil
}

func (m *SetResourceRequest) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *SetResourceRequest) GetAlgorithm() string {
	if m != nil {
		return m.Algorithm
	}
	return ""
}

func (m *SetResourceRequest) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

type GetGroupResponse struct {
	Payload              []byte   `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	PayloadVersion       string   `protobuf:"bytes,2,opt,name=payload_version,json=payloadVersion,proto3" json:"payload_version,omitempty"`
	HashAlgorithm        string   `protobuf:"bytes,3,opt,name=hash_algorithm,json=hashAlgorithm,proto3" json:"hash_algorithm,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGroupResponse) Reset()         { *m = GetGroupResponse{} }
func (m *GetGroupResponse) String() string { return proto.CompactTextString(m) }
func (*GetGroupResponse) ProtoMessage()    {}
func (*GetGroupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_383081686ffb1987, []int{1}
}

func (m *GetGroupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGroupResponse.Unmarshal(m, b)
}
func (m *GetGroupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGroupResponse.Marshal(b, m, deterministic)
}
func (m *GetGroupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGroupResponse.Merge(m, src)
}
func (m *GetGroupResponse) XXX_Size() int {
	return xxx_messageInfo_GetGroupResponse.Size(m)
}
func (m *GetGroupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGroupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetGroupResponse proto.InternalMessageInfo

func (m *GetGroupResponse) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *GetGroupResponse) GetPayloadVersion() string {
	if m != nil {
		return m.PayloadVersion
	}
	return ""
}

func (m *GetGroupResponse) GetHashAlgorithm() string {
	if m != nil {
		return m.HashAlgorithm
	}
	return ""
}

type GetStatRequest struct {
	Versions             []string `protobuf:"bytes,1,rep,name=versions,proto3" json:"versions,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStatRequest) Reset()         { *m = GetStatRequest{} }
func (m *GetStatRequest) String() string { return proto.CompactTextString(m) }
func (*GetStatRequest) ProtoMessage()    {}
func (*GetStatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_383081686ffb1987, []int{2}
}

func (m *GetStatRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStatRequest.Unmarshal(m, b)
}
func (m *GetStatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStatRequest.Marshal(b, m, deterministic)
}
func (m *GetStatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStatRequest.Merge(m, src)
}
func (m *GetStatRequest) XXX_Size() int {
	return xxx_messageInfo_GetStatRequest.Size(m)
}
func (m *GetStatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetStatRequest proto.InternalMessageInfo

func (m *GetStatRequest) GetVersions() []string {
	if m != nil {
		return m.Versions
	}
	return nil
}

type GetStatResponse struct {
	Payloads             map[string]*GetStatEntry `protobuf:"bytes,1,rep,name=payloads,proto3" json:"payloads,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *GetStatResponse) Reset()         { *m = GetStatResponse{} }
func (m *GetStatResponse) String() string { return proto.CompactTextString(m) }
func (*GetStatResponse) ProtoMessage()    {}
func (*GetStatResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_383081686ffb1987, []int{3}
}

func (m *GetStatResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStatResponse.Unmarshal(m, b)
}
func (m *GetStatResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStatResponse.Marshal(b, m, deterministic)
}
func (m *GetStatResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStatResponse.Merge(m, src)
}
func (m *GetStatResponse) XXX_Size() int {
	return xxx_messageInfo_GetStatResponse.Size(m)
}
func (m *GetStatResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStatResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetStatResponse proto.InternalMessageInfo

func (m *GetStatResponse) GetPayloads() map[string]*GetStatEntry {
	if m != nil {
		return m.Payloads
	}
	return nil
}

type GetStatEntry struct {
	Payload              []byte               `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	PayloadVersion       string               `protobuf:"bytes,2,opt,name=payload_version,json=payloadVersion,proto3" json:"payload_version,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetStatEntry) Reset()         { *m = GetStatEntry{} }
func (m *GetStatEntry) String() string { return proto.CompactTextString(m) }
func (*GetStatEntry) ProtoMessage()    {}
func (*GetStatEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_383081686ffb1987, []int{4}
}

func (m *GetStatEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStatEntry.Unmarshal(m, b)
}
func (m *GetStatEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStatEntry.Marshal(b, m, deterministic)
}
func (m *GetStatEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStatEntry.Merge(m, src)
}
func (m *GetStatEntry) XXX_Size() int {
	return xxx_messageInfo_GetStatEntry.Size(m)
}
func (m *GetStatEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStatEntry.DiscardUnknown(m)
}

var xxx_messageInfo_GetStatEntry proto.InternalMessageInfo

func (m *GetStatEntry) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *GetStatEntry) GetPayloadVersion() string {
	if m != nil {
		return m.PayloadVersion
	}
	return ""
}

func (m *GetStatEntry) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

type GetGroupFileHashResponse struct {
	FileHash             []string `protobuf:"bytes,1,rep,name=file_hash,json=fileHash,proto3" json:"file_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGroupFileHashResponse) Reset()         { *m = GetGroupFileHashResponse{} }
func (m *GetGroupFileHashResponse) String() string { return proto.CompactTextString(m) }
func (*GetGroupFileHashResponse) ProtoMessage()    {}
func (*GetGroupFileHashResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_383081686ffb1987, []int{5}
}

func (m *GetGroupFileHashResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGroupFileHashResponse.Unmarshal(m, b)
}
func (m *GetGroupFileHashResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGroupFileHashResponse.Marshal(b, m, deterministic)
}
func (m *GetGroupFileHashResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGroupFileHashResponse.Merge(m, src)
}
func (m *GetGroupFileHashResponse) XXX_Size() int {
	return xxx_messageInfo_GetGroupFileHashResponse.Size(m)
}
func (m *GetGroupFileHashResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGroupFileHashResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetGroupFileHashResponse proto.InternalMessageInfo

func (m *GetGroupFileHashResponse) GetFileHash() []string {
	if m != nil {
		return m.FileHash
	}
	return nil
}

type SetFileMetaRequest struct {
	OrgId                string   `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	ResourceId           string   `protobuf:"bytes,2,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	FileName             string   `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileHash             string   `protobuf:"bytes,4,opt,name=file_hash,json=fileHash,proto3" json:"file_hash,omitempty"`
	FileSize             string   `protobuf:"bytes,5,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	Remark               string   `protobuf:"bytes,6,opt,name=remark,proto3" json:"remark,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetFileMetaRequest) Reset()         { *m = SetFileMetaRequest{} }
func (m *SetFileMetaRequest) String() string { return proto.CompactTextString(m) }
func (*SetFileMetaRequest) ProtoMessage()    {}
func (*SetFileMetaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_383081686ffb1987, []int{6}
}

func (m *SetFileMetaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetFileMetaRequest.Unmarshal(m, b)
}
func (m *SetFileMetaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetFileMetaRequest.Marshal(b, m, deterministic)
}
func (m *SetFileMetaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetFileMetaRequest.Merge(m, src)
}
func (m *SetFileMetaRequest) XXX_Size() int {
	return xxx_messageInfo_SetFileMetaRequest.Size(m)
}
func (m *SetFileMetaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetFileMetaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetFileMetaRequest proto.InternalMessageInfo

func (m *SetFileMetaRequest) GetOrgId() string {
	if m != nil {
		return m.OrgId
	}
	return ""
}

func (m *SetFileMetaRequest) GetResourceId() string {
	if m != nil {
		return m.ResourceId
	}
	return ""
}

func (m *SetFileMetaRequest) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *SetFileMetaRequest) GetFileHash() string {
	if m != nil {
		return m.FileHash
	}
	return ""
}

func (m *SetFileMetaRequest) GetFileSize() string {
	if m != nil {
		return m.FileSize
	}
	return ""
}

func (m *SetFileMetaRequest) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

type SetTableMetaRequest struct {
	Payload              []byte   `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	OrgId                string   `protobuf:"bytes,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	ResourceId           string   `protobuf:"bytes,3,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	AddrHash             string   `protobuf:"bytes,4,opt,name=addrHash,proto3" json:"addrHash,omitempty"`
	DbName               string   `protobuf:"bytes,5,opt,name=db_name,json=dbName,proto3" json:"db_name,omitempty"`
	Remark               string   `protobuf:"bytes,6,opt,name=remark,proto3" json:"remark,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetTableMetaRequest) Reset()         { *m = SetTableMetaRequest{} }
func (m *SetTableMetaRequest) String() string { return proto.CompactTextString(m) }
func (*SetTableMetaRequest) ProtoMessage()    {}
func (*SetTableMetaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_383081686ffb1987, []int{7}
}

func (m *SetTableMetaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetTableMetaRequest.Unmarshal(m, b)
}
func (m *SetTableMetaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetTableMetaRequest.Marshal(b, m, deterministic)
}
func (m *SetTableMetaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetTableMetaRequest.Merge(m, src)
}
func (m *SetTableMetaRequest) XXX_Size() int {
	return xxx_messageInfo_SetTableMetaRequest.Size(m)
}
func (m *SetTableMetaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetTableMetaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetTableMetaRequest proto.InternalMessageInfo

func (m *SetTableMetaRequest) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *SetTableMetaRequest) GetOrgId() string {
	if m != nil {
		return m.OrgId
	}
	return ""
}

func (m *SetTableMetaRequest) GetResourceId() string {
	if m != nil {
		return m.ResourceId
	}
	return ""
}

func (m *SetTableMetaRequest) GetAddrHash() string {
	if m != nil {
		return m.AddrHash
	}
	return ""
}

func (m *SetTableMetaRequest) GetDbName() string {
	if m != nil {
		return m.DbName
	}
	return ""
}

func (m *SetTableMetaRequest) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

type SetAuthorityRecordRequest struct {
	OwnerOrgId           string               `protobuf:"bytes,1,opt,name=owner_org_id,json=ownerOrgId,proto3" json:"owner_org_id,omitempty"`
	AuthorityOrgId       string               `protobuf:"bytes,2,opt,name=authority_org_id,json=authorityOrgId,proto3" json:"authority_org_id,omitempty"`
	AuthorityDataId      string               `protobuf:"bytes,3,opt,name=authority_data_id,json=authorityDataId,proto3" json:"authority_data_id,omitempty"`
	PeriodOfValidate     int64                `protobuf:"varint,4,opt,name=period_of_validate,json=periodOfValidate,proto3" json:"period_of_validate,omitempty"`
	Remark               string               `protobuf:"bytes,5,opt,name=remark,proto3" json:"remark,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SetAuthorityRecordRequest) Reset()         { *m = SetAuthorityRecordRequest{} }
func (m *SetAuthorityRecordRequest) String() string { return proto.CompactTextString(m) }
func (*SetAuthorityRecordRequest) ProtoMessage()    {}
func (*SetAuthorityRecordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_383081686ffb1987, []int{8}
}

func (m *SetAuthorityRecordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetAuthorityRecordRequest.Unmarshal(m, b)
}
func (m *SetAuthorityRecordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetAuthorityRecordRequest.Marshal(b, m, deterministic)
}
func (m *SetAuthorityRecordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetAuthorityRecordRequest.Merge(m, src)
}
func (m *SetAuthorityRecordRequest) XXX_Size() int {
	return xxx_messageInfo_SetAuthorityRecordRequest.Size(m)
}
func (m *SetAuthorityRecordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetAuthorityRecordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetAuthorityRecordRequest proto.InternalMessageInfo

func (m *SetAuthorityRecordRequest) GetOwnerOrgId() string {
	if m != nil {
		return m.OwnerOrgId
	}
	return ""
}

func (m *SetAuthorityRecordRequest) GetAuthorityOrgId() string {
	if m != nil {
		return m.AuthorityOrgId
	}
	return ""
}

func (m *SetAuthorityRecordRequest) GetAuthorityDataId() string {
	if m != nil {
		return m.AuthorityDataId
	}
	return ""
}

func (m *SetAuthorityRecordRequest) GetPeriodOfValidate() int64 {
	if m != nil {
		return m.PeriodOfValidate
	}
	return 0
}

func (m *SetAuthorityRecordRequest) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *SetAuthorityRecordRequest) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func init() {
	proto.RegisterType((*SetResourceRequest)(nil), "adopter.SetResourceRequest")
	proto.RegisterType((*GetGroupResponse)(nil), "adopter.GetGroupResponse")
	proto.RegisterType((*GetStatRequest)(nil), "adopter.GetStatRequest")
	proto.RegisterType((*GetStatResponse)(nil), "adopter.GetStatResponse")
	proto.RegisterMapType((map[string]*GetStatEntry)(nil), "adopter.GetStatResponse.PayloadsEntry")
	proto.RegisterType((*GetStatEntry)(nil), "adopter.GetStatEntry")
	proto.RegisterType((*GetGroupFileHashResponse)(nil), "adopter.GetGroupFileHashResponse")
	proto.RegisterType((*SetFileMetaRequest)(nil), "adopter.SetFileMetaRequest")
	proto.RegisterType((*SetTableMetaRequest)(nil), "adopter.SetTableMetaRequest")
	proto.RegisterType((*SetAuthorityRecordRequest)(nil), "adopter.SetAuthorityRecordRequest")
}

func init() {
	proto.RegisterFile("protos/adopter/adopter-api-v1.proto", fileDescriptor_383081686ffb1987)
}

var fileDescriptor_383081686ffb1987 = []byte{
	// 673 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xc1, 0x6e, 0xd3, 0x4a,
	0x14, 0x95, 0x93, 0x26, 0x6d, 0x6e, 0xda, 0x34, 0x6f, 0x9e, 0xfa, 0x9e, 0x09, 0x48, 0x8d, 0x82,
	0x80, 0x08, 0x5a, 0x47, 0x14, 0x04, 0x15, 0xbb, 0x56, 0x40, 0xdb, 0x05, 0x14, 0x39, 0x55, 0x17,
	0x6c, 0xac, 0x49, 0xe6, 0x26, 0xb1, 0x6a, 0x67, 0xdc, 0xf1, 0x38, 0x28, 0x15, 0x7f, 0xc0, 0x92,
	0xaf, 0x60, 0xcf, 0x8e, 0x9f, 0x43, 0x1e, 0xcf, 0xd8, 0x49, 0x51, 0x2b, 0x55, 0x62, 0x93, 0xcc,
	0x3d, 0xe7, 0x8c, 0xe7, 0x9c, 0xb9, 0xd7, 0x86, 0x87, 0x91, 0xe0, 0x92, 0xc7, 0x3d, 0xca, 0x78,
	0x24, 0x51, 0x98, 0xff, 0x5d, 0x1a, 0xf9, 0xbb, 0xb3, 0xe7, 0x8e, 0x62, 0xc9, 0xaa, 0x46, 0x5b,
	0xdb, 0x63, 0xce, 0xc7, 0x01, 0xf6, 0x14, 0x3c, 0x48, 0x46, 0x3d, 0xe9, 0x87, 0x18, 0x4b, 0x1a,
	0x46, 0x99, 0xb2, 0xf3, 0xd3, 0x02, 0xd2, 0x47, 0xe9, 0x62, 0xcc, 0x13, 0x31, 0x44, 0x17, 0x2f,
	0x13, 0x8c, 0x25, 0xb1, 0x61, 0x35, 0xa2, 0xf3, 0x80, 0x53, 0x66, 0x5b, 0x6d, 0xab, 0xbb, 0xee,
	0x9a, 0x92, 0x10, 0x58, 0x09, 0xf8, 0x38, 0xb6, 0x4b, 0x0a, 0x56, 0xeb, 0x54, 0x3d, 0x43, 0x11,
	0xfb, 0x7c, 0x6a, 0x97, 0xdb, 0x56, 0xb7, 0xe6, 0x9a, 0x92, 0x3c, 0x80, 0x1a, 0x0d, 0xc6, 0x5c,
	0xf8, 0x72, 0x12, 0xda, 0x2b, 0x8a, 0x2b, 0x00, 0xb2, 0x0f, 0xb5, 0xdc, 0x8f, 0x5d, 0x69, 0x5b,
	0xdd, 0xfa, 0x5e, 0xcb, 0xc9, 0x1c, 0x3b, 0xc6, 0xb1, 0x73, 0x66, 0x14, 0x6e, 0x21, 0xee, 0x7c,
	0x85, 0xe6, 0x11, 0xca, 0x23, 0xc1, 0x93, 0xc8, 0xc5, 0x38, 0xe2, 0xd3, 0x18, 0x6f, 0xf1, 0xfc,
	0x04, 0x36, 0xf5, 0xd2, 0x33, 0x3e, 0x4b, 0xca, 0x4b, 0x43, 0xc3, 0xe7, 0xda, 0xee, 0x23, 0x68,
	0x4c, 0x68, 0x3c, 0xf1, 0x0a, 0xcf, 0x59, 0x9e, 0x8d, 0x14, 0x3d, 0x30, 0x60, 0x67, 0x07, 0x1a,
	0x47, 0x28, 0xfb, 0x92, 0x4a, 0x73, 0x5f, 0x2d, 0x58, 0xd3, 0x4f, 0x8e, 0x6d, 0xab, 0x5d, 0xee,
	0xd6, 0xdc, 0xbc, 0xee, 0xfc, 0xb0, 0x60, 0x33, 0x97, 0x6b, 0xaf, 0x87, 0xb0, 0xa6, 0x8f, 0xce,
	0xf4, 0xf5, 0xbd, 0xc7, 0x8e, 0xee, 0x99, 0x73, 0x4d, 0xeb, 0x7c, 0xd2, 0xc2, 0x77, 0x53, 0x29,
	0xe6, 0x6e, 0xbe, 0xaf, 0xe5, 0xc2, 0xc6, 0x12, 0x45, 0x9a, 0x50, 0xbe, 0xc0, 0xb9, 0x0a, 0x5f,
	0x73, 0xd3, 0x25, 0x79, 0x06, 0x95, 0x19, 0x0d, 0x12, 0x54, 0x71, 0xeb, 0x7b, 0x5b, 0xd7, 0xcf,
	0xc8, 0x1e, 0x99, 0x69, 0xde, 0x94, 0xf6, 0xad, 0xce, 0x37, 0x0b, 0xd6, 0x17, 0xb9, 0xbf, 0x71,
	0xa9, 0x4b, 0x5d, 0x2e, 0xdf, 0xa5, 0xcb, 0xaf, 0xc1, 0x36, 0x5d, 0x7e, 0xef, 0x07, 0x78, 0x4c,
	0xe3, 0x49, 0x7e, 0x83, 0xf7, 0xa1, 0x36, 0xf2, 0x03, 0xf4, 0xd2, 0xce, 0x98, 0x2b, 0x1f, 0x69,
	0x51, 0xe7, 0x57, 0x36, 0xd5, 0xe9, 0xa6, 0x0f, 0x28, 0xa9, 0xe9, 0xd2, 0x16, 0x54, 0xb9, 0x18,
	0x7b, 0x3e, 0xd3, 0x77, 0x54, 0xe1, 0x62, 0x7c, 0xc2, 0xc8, 0x36, 0xd4, 0x85, 0x9e, 0xff, 0x94,
	0xcb, 0x52, 0x80, 0x81, 0x4e, 0x58, 0x7e, 0xd6, 0x94, 0x86, 0xa8, 0x27, 0x42, 0x9d, 0xf5, 0x91,
	0x86, 0xd7, 0x8c, 0xac, 0x14, 0x64, 0x6a, 0x24, 0x27, 0x63, 0xff, 0x0a, 0xd5, 0x84, 0x6b, 0xb2,
	0xef, 0x5f, 0x21, 0xf9, 0x0f, 0xaa, 0x02, 0x43, 0x2a, 0x2e, 0xec, 0xaa, 0x62, 0x74, 0x95, 0xbe,
	0x93, 0xff, 0xf6, 0x51, 0x9e, 0xd1, 0xc1, 0xb2, 0xfd, 0x9b, 0x7b, 0x51, 0x04, 0x2b, 0xdd, 0x12,
	0xac, 0xfc, 0x47, 0xb0, 0x16, 0xac, 0x51, 0xc6, 0xc4, 0xf1, 0x82, 0x75, 0x53, 0x93, 0xff, 0x61,
	0x95, 0x0d, 0xb2, 0xc8, 0x99, 0xf1, 0x2a, 0x1b, 0xa8, 0xc0, 0x37, 0xd9, 0xfe, 0x5e, 0x82, 0x7b,
	0x7d, 0x94, 0x07, 0x89, 0x9c, 0xa4, 0xef, 0xc9, 0xdc, 0xc5, 0x21, 0x17, 0xcc, 0x98, 0x6f, 0xc3,
	0x3a, 0xff, 0x32, 0x45, 0xe1, 0x2d, 0x75, 0x00, 0x14, 0x76, 0xaa, 0xdc, 0x76, 0xa1, 0x49, 0xcd,
	0x5e, 0x6f, 0x29, 0x4e, 0x23, 0xc7, 0x33, 0xe5, 0x53, 0xf8, 0xa7, 0x50, 0x32, 0x2a, 0x69, 0x91,
	0x6e, 0x33, 0x27, 0xde, 0x52, 0x49, 0x4f, 0x18, 0xd9, 0x01, 0x12, 0xa1, 0xf0, 0x39, 0xf3, 0xf8,
	0xc8, 0x9b, 0xd1, 0xc0, 0x67, 0x54, 0xa2, 0x0a, 0x5b, 0x76, 0x9b, 0x19, 0x73, 0x3a, 0x3a, 0xd7,
	0xf8, 0x42, 0xb6, 0xca, 0x62, 0xb6, 0xe5, 0x19, 0xae, 0xde, 0x61, 0x86, 0x0f, 0x5f, 0x7d, 0x7e,
	0x39, 0xf6, 0xa5, 0x73, 0x99, 0xa0, 0x98, 0x0f, 0x69, 0xe4, 0x0c, 0x79, 0xd8, 0x1b, 0x06, 0x3c,
	0x61, 0xc3, 0x09, 0xf5, 0xa7, 0x3d, 0xf5, 0x3b, 0xe4, 0x4c, 0x7f, 0xa2, 0xf3, 0xef, 0xfa, 0xa0,
	0xaa, 0xea, 0x17, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x13, 0x3f, 0x97, 0x8f, 0xf0, 0x05, 0x00,
	0x00,
}
