// Code generated by protoc-gen-go. DO NOT EDIT.
// source: git.querycap.com/cloudchain/chaincode/protos/adopter/adopter-v1.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GMetadataV1 struct {
	Timestamp *timestamp.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// The version of the group
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// The hash algorithm's name
	HashAlgorithm        string   `protobuf:"bytes,3,opt,name=hash_algorithm,json=hashAlgorithm,proto3" json:"hash_algorithm,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GMetadataV1) Reset()         { *m = GMetadataV1{} }
func (m *GMetadataV1) String() string { return proto.CompactTextString(m) }
func (*GMetadataV1) ProtoMessage()    {}
func (*GMetadataV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_992219a3bb471cb5, []int{0}
}

func (m *GMetadataV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GMetadataV1.Unmarshal(m, b)
}
func (m *GMetadataV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GMetadataV1.Marshal(b, m, deterministic)
}
func (m *GMetadataV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GMetadataV1.Merge(m, src)
}
func (m *GMetadataV1) XXX_Size() int {
	return xxx_messageInfo_GMetadataV1.Size(m)
}
func (m *GMetadataV1) XXX_DiscardUnknown() {
	xxx_messageInfo_GMetadataV1.DiscardUnknown(m)
}

var xxx_messageInfo_GMetadataV1 proto.InternalMessageInfo

func (m *GMetadataV1) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *GMetadataV1) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *GMetadataV1) GetHashAlgorithm() string {
	if m != nil {
		return m.HashAlgorithm
	}
	return ""
}

type SMetadataV1 struct {
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Version              string               `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SMetadataV1) Reset()         { *m = SMetadataV1{} }
func (m *SMetadataV1) String() string { return proto.CompactTextString(m) }
func (*SMetadataV1) ProtoMessage()    {}
func (*SMetadataV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_992219a3bb471cb5, []int{1}
}

func (m *SMetadataV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SMetadataV1.Unmarshal(m, b)
}
func (m *SMetadataV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SMetadataV1.Marshal(b, m, deterministic)
}
func (m *SMetadataV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SMetadataV1.Merge(m, src)
}
func (m *SMetadataV1) XXX_Size() int {
	return xxx_messageInfo_SMetadataV1.Size(m)
}
func (m *SMetadataV1) XXX_DiscardUnknown() {
	xxx_messageInfo_SMetadataV1.DiscardUnknown(m)
}

var xxx_messageInfo_SMetadataV1 proto.InternalMessageInfo

func (m *SMetadataV1) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *SMetadataV1) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type GroupData struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupData) Reset()         { *m = GroupData{} }
func (m *GroupData) String() string { return proto.CompactTextString(m) }
func (*GroupData) ProtoMessage()    {}
func (*GroupData) Descriptor() ([]byte, []int) {
	return fileDescriptor_992219a3bb471cb5, []int{2}
}

func (m *GroupData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupData.Unmarshal(m, b)
}
func (m *GroupData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupData.Marshal(b, m, deterministic)
}
func (m *GroupData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupData.Merge(m, src)
}
func (m *GroupData) XXX_Size() int {
	return xxx_messageInfo_GroupData.Size(m)
}
func (m *GroupData) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupData.DiscardUnknown(m)
}

var xxx_messageInfo_GroupData proto.InternalMessageInfo

func (m *GroupData) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *GroupData) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type GroupMetadata struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Metadata             []byte   `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupMetadata) Reset()         { *m = GroupMetadata{} }
func (m *GroupMetadata) String() string { return proto.CompactTextString(m) }
func (*GroupMetadata) ProtoMessage()    {}
func (*GroupMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_992219a3bb471cb5, []int{3}
}

func (m *GroupMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupMetadata.Unmarshal(m, b)
}
func (m *GroupMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupMetadata.Marshal(b, m, deterministic)
}
func (m *GroupMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupMetadata.Merge(m, src)
}
func (m *GroupMetadata) XXX_Size() int {
	return xxx_messageInfo_GroupMetadata.Size(m)
}
func (m *GroupMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_GroupMetadata proto.InternalMessageInfo

func (m *GroupMetadata) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *GroupMetadata) GetMetadata() []byte {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type Group struct {
	Data                 *GroupData     `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Metadata             *GroupMetadata `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Group) Reset()         { *m = Group{} }
func (m *Group) String() string { return proto.CompactTextString(m) }
func (*Group) ProtoMessage()    {}
func (*Group) Descriptor() ([]byte, []int) {
	return fileDescriptor_992219a3bb471cb5, []int{4}
}

func (m *Group) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Group.Unmarshal(m, b)
}
func (m *Group) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Group.Marshal(b, m, deterministic)
}
func (m *Group) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Group.Merge(m, src)
}
func (m *Group) XXX_Size() int {
	return xxx_messageInfo_Group.Size(m)
}
func (m *Group) XXX_DiscardUnknown() {
	xxx_messageInfo_Group.DiscardUnknown(m)
}

var xxx_messageInfo_Group proto.InternalMessageInfo

func (m *Group) GetData() *GroupData {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Group) GetMetadata() *GroupMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type StatMetadata struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Metadata             []byte   `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatMetadata) Reset()         { *m = StatMetadata{} }
func (m *StatMetadata) String() string { return proto.CompactTextString(m) }
func (*StatMetadata) ProtoMessage()    {}
func (*StatMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_992219a3bb471cb5, []int{5}
}

func (m *StatMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatMetadata.Unmarshal(m, b)
}
func (m *StatMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatMetadata.Marshal(b, m, deterministic)
}
func (m *StatMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatMetadata.Merge(m, src)
}
func (m *StatMetadata) XXX_Size() int {
	return xxx_messageInfo_StatMetadata.Size(m)
}
func (m *StatMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_StatMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_StatMetadata proto.InternalMessageInfo

func (m *StatMetadata) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *StatMetadata) GetMetadata() []byte {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type StatData struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatData) Reset()         { *m = StatData{} }
func (m *StatData) String() string { return proto.CompactTextString(m) }
func (*StatData) ProtoMessage()    {}
func (*StatData) Descriptor() ([]byte, []int) {
	return fileDescriptor_992219a3bb471cb5, []int{6}
}

func (m *StatData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatData.Unmarshal(m, b)
}
func (m *StatData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatData.Marshal(b, m, deterministic)
}
func (m *StatData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatData.Merge(m, src)
}
func (m *StatData) XXX_Size() int {
	return xxx_messageInfo_StatData.Size(m)
}
func (m *StatData) XXX_DiscardUnknown() {
	xxx_messageInfo_StatData.DiscardUnknown(m)
}

var xxx_messageInfo_StatData proto.InternalMessageInfo

func (m *StatData) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *StatData) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Stat struct {
	Data                 *StatData     `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Metadata             *StatMetadata `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Stat) Reset()         { *m = Stat{} }
func (m *Stat) String() string { return proto.CompactTextString(m) }
func (*Stat) ProtoMessage()    {}
func (*Stat) Descriptor() ([]byte, []int) {
	return fileDescriptor_992219a3bb471cb5, []int{7}
}

func (m *Stat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Stat.Unmarshal(m, b)
}
func (m *Stat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Stat.Marshal(b, m, deterministic)
}
func (m *Stat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Stat.Merge(m, src)
}
func (m *Stat) XXX_Size() int {
	return xxx_messageInfo_Stat.Size(m)
}
func (m *Stat) XXX_DiscardUnknown() {
	xxx_messageInfo_Stat.DiscardUnknown(m)
}

var xxx_messageInfo_Stat proto.InternalMessageInfo

func (m *Stat) GetData() *StatData {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Stat) GetMetadata() *StatMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func init() {
	proto.RegisterType((*GMetadataV1)(nil), "adopter.GMetadataV1")
	proto.RegisterType((*SMetadataV1)(nil), "adopter.SMetadataV1")
	proto.RegisterType((*GroupData)(nil), "adopter.GroupData")
	proto.RegisterType((*GroupMetadata)(nil), "adopter.GroupMetadata")
	proto.RegisterType((*Group)(nil), "adopter.Group")
	proto.RegisterType((*StatMetadata)(nil), "adopter.StatMetadata")
	proto.RegisterType((*StatData)(nil), "adopter.StatData")
	proto.RegisterType((*Stat)(nil), "adopter.Stat")
}

func init() {
	proto.RegisterFile("git.querycap.com/cloudchain/chaincode/protos/adopter/adopter-v1.proto", fileDescriptor_992219a3bb471cb5)
}

var fileDescriptor_992219a3bb471cb5 = []byte{
	// 343 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x93, 0x41, 0x4f, 0xbb, 0x40,
	0x10, 0xc5, 0xc3, 0xff, 0x5f, 0x6d, 0x3b, 0xb4, 0x26, 0x6e, 0xa2, 0x21, 0xbd, 0xd8, 0x90, 0xd4,
	0xf4, 0xe2, 0x92, 0x56, 0x63, 0xea, 0x51, 0xd3, 0xa6, 0x27, 0x2f, 0xad, 0xf1, 0xe0, 0x45, 0xa7,
	0x80, 0x40, 0x02, 0x5d, 0x5c, 0x96, 0x26, 0x7e, 0x03, 0x3f, 0xb6, 0x61, 0xd9, 0xc5, 0x62, 0x13,
	0x0f, 0x35, 0x5e, 0x80, 0x19, 0x7e, 0xf3, 0xe6, 0x3d, 0xc8, 0xc2, 0x2c, 0x88, 0x04, 0x7d, 0xcb,
	0x7d, 0xfe, 0xee, 0x62, 0x4a, 0x5d, 0x96, 0x38, 0x6e, 0xcc, 0x72, 0xcf, 0x0d, 0x31, 0x5a, 0x3b,
	0xf2, 0xea, 0x32, 0xcf, 0x77, 0x52, 0xce, 0x04, 0xcb, 0x1c, 0xf4, 0x58, 0x2a, 0x7c, 0xae, 0xef,
	0x17, 0x9b, 0x11, 0x95, 0x6f, 0x48, 0x53, 0x75, 0x7a, 0x67, 0x01, 0x63, 0x41, 0xac, 0x06, 0x56,
	0xf9, 0xab, 0x23, 0xa2, 0xc4, 0xcf, 0x04, 0x26, 0x69, 0x49, 0xda, 0x1f, 0x06, 0x98, 0xf3, 0x7b,
	0x5f, 0xa0, 0x87, 0x02, 0x1f, 0x47, 0x64, 0x02, 0xed, 0x0a, 0xb1, 0x8c, 0xbe, 0x31, 0x34, 0xc7,
	0x3d, 0x5a, 0x8a, 0x50, 0x2d, 0x42, 0x1f, 0x34, 0xb1, 0xf8, 0x82, 0x89, 0x05, 0xcd, 0x8d, 0xcf,
	0xb3, 0x88, 0xad, 0xad, 0x7f, 0x7d, 0x63, 0xd8, 0x5e, 0xe8, 0x92, 0x0c, 0xe0, 0x28, 0xc4, 0x2c,
	0x7c, 0xc6, 0x38, 0x60, 0x3c, 0x12, 0x61, 0x62, 0xfd, 0x97, 0x40, 0xb7, 0xe8, 0xde, 0xea, 0xa6,
	0x8d, 0x60, 0x2e, 0xff, 0xd6, 0x89, 0x7d, 0x03, 0xed, 0x39, 0x67, 0x79, 0x3a, 0x45, 0x81, 0xdb,
	0x98, 0x51, 0x37, 0x4c, 0xa0, 0x51, 0x98, 0x90, 0xd3, 0x9d, 0x85, 0x7c, 0xb6, 0x67, 0xd0, 0x95,
	0xa3, 0xda, 0xe1, 0x0f, 0xe3, 0x3d, 0x68, 0x25, 0x8a, 0x52, 0x12, 0x55, 0x6d, 0xbb, 0x70, 0x20,
	0x65, 0xc8, 0xb9, 0xda, 0x51, 0x26, 0x23, 0x54, 0xfd, 0x31, 0x5a, 0xf9, 0x2b, 0xf7, 0x92, 0xf1,
	0x37, 0x31, 0x73, 0x7c, 0x5a, 0x67, 0xb5, 0xa1, 0xad, 0x25, 0x53, 0xe8, 0x2c, 0x05, 0x8a, 0x5f,
	0x5a, 0x9d, 0x40, 0xab, 0x50, 0xd9, 0xe3, 0x5b, 0xbd, 0x40, 0xa3, 0x98, 0x24, 0x83, 0x5a, 0xc6,
	0xe3, 0xca, 0xb7, 0x96, 0x55, 0x11, 0x47, 0x3b, 0x11, 0x4f, 0x6a, 0xe8, 0x6e, 0xc2, 0xbb, 0xeb,
	0xa7, 0xab, 0x7d, 0x4e, 0xca, 0xea, 0x50, 0xd6, 0x97, 0x9f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x19,
	0x91, 0x8d, 0x14, 0x68, 0x03, 0x00, 0x00,
}
