proto-forest:
	protoc --proto_path=protos/forest --go_out=protos/forest forest.proto

build-rock:
	go build -o cmd-rock github.com/waylennn/chaincode/adopter/rock/cmd

build-forest:
	go build -o cmd-forest github.com/waylennn/chaincode/adopter/forest/cmd

build-adopter:
	go build -o cmd-adopter github.com/waylennn/chaincode/adopter/github.com/waylennn/chaincode/adopter/cmd
