// Code generated by protoc-gen-go. DO NOT EDIT.
// source: adopter-v2.proto

package adopter

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FileV2 struct {
	FileName             string   `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileHash             string   `protobuf:"bytes,2,opt,name=file_hash,json=fileHash,proto3" json:"file_hash,omitempty"`
	FileSize             uint32   `protobuf:"varint,3,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	Logs                 []byte   `protobuf:"bytes,4,opt,name=logs,proto3" json:"logs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileV2) Reset()         { *m = FileV2{} }
func (m *FileV2) String() string { return proto.CompactTextString(m) }
func (*FileV2) ProtoMessage()    {}
func (*FileV2) Descriptor() ([]byte, []int) {
	return fileDescriptor_f393e68fe5690326, []int{0}
}

func (m *FileV2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileV2.Unmarshal(m, b)
}
func (m *FileV2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileV2.Marshal(b, m, deterministic)
}
func (m *FileV2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileV2.Merge(m, src)
}
func (m *FileV2) XXX_Size() int {
	return xxx_messageInfo_FileV2.Size(m)
}
func (m *FileV2) XXX_DiscardUnknown() {
	xxx_messageInfo_FileV2.DiscardUnknown(m)
}

var xxx_messageInfo_FileV2 proto.InternalMessageInfo

func (m *FileV2) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *FileV2) GetFileHash() string {
	if m != nil {
		return m.FileHash
	}
	return ""
}

func (m *FileV2) GetFileSize() uint32 {
	if m != nil {
		return m.FileSize
	}
	return 0
}

func (m *FileV2) GetLogs() []byte {
	if m != nil {
		return m.Logs
	}
	return nil
}

type FileMeta struct {
	OrgId                string    `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Remark               string    `protobuf:"bytes,2,opt,name=remark,proto3" json:"remark,omitempty"`
	Files                []*FileV2 `protobuf:"bytes,3,rep,name=files,proto3" json:"files,omitempty"`
	Timestamp            uint64    `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *FileMeta) Reset()         { *m = FileMeta{} }
func (m *FileMeta) String() string { return proto.CompactTextString(m) }
func (*FileMeta) ProtoMessage()    {}
func (*FileMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_f393e68fe5690326, []int{1}
}

func (m *FileMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileMeta.Unmarshal(m, b)
}
func (m *FileMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileMeta.Marshal(b, m, deterministic)
}
func (m *FileMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileMeta.Merge(m, src)
}
func (m *FileMeta) XXX_Size() int {
	return xxx_messageInfo_FileMeta.Size(m)
}
func (m *FileMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_FileMeta.DiscardUnknown(m)
}

var xxx_messageInfo_FileMeta proto.InternalMessageInfo

func (m *FileMeta) GetOrgId() string {
	if m != nil {
		return m.OrgId
	}
	return ""
}

func (m *FileMeta) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *FileMeta) GetFiles() []*FileV2 {
	if m != nil {
		return m.Files
	}
	return nil
}

func (m *FileMeta) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type TableV2 struct {
	TableName            string   `protobuf:"bytes,1,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	TableHash            string   `protobuf:"bytes,2,opt,name=table_hash,json=tableHash,proto3" json:"table_hash,omitempty"`
	Logs                 []byte   `protobuf:"bytes,3,opt,name=logs,proto3" json:"logs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TableV2) Reset()         { *m = TableV2{} }
func (m *TableV2) String() string { return proto.CompactTextString(m) }
func (*TableV2) ProtoMessage()    {}
func (*TableV2) Descriptor() ([]byte, []int) {
	return fileDescriptor_f393e68fe5690326, []int{2}
}

func (m *TableV2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TableV2.Unmarshal(m, b)
}
func (m *TableV2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TableV2.Marshal(b, m, deterministic)
}
func (m *TableV2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TableV2.Merge(m, src)
}
func (m *TableV2) XXX_Size() int {
	return xxx_messageInfo_TableV2.Size(m)
}
func (m *TableV2) XXX_DiscardUnknown() {
	xxx_messageInfo_TableV2.DiscardUnknown(m)
}

var xxx_messageInfo_TableV2 proto.InternalMessageInfo

func (m *TableV2) GetTableName() string {
	if m != nil {
		return m.TableName
	}
	return ""
}

func (m *TableV2) GetTableHash() string {
	if m != nil {
		return m.TableHash
	}
	return ""
}

func (m *TableV2) GetLogs() []byte {
	if m != nil {
		return m.Logs
	}
	return nil
}

type DatabaseV2 struct {
	DbName               string     `protobuf:"bytes,1,opt,name=db_name,json=dbName,proto3" json:"db_name,omitempty"`
	Tables               []*TableV2 `protobuf:"bytes,2,rep,name=tables,proto3" json:"tables,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *DatabaseV2) Reset()         { *m = DatabaseV2{} }
func (m *DatabaseV2) String() string { return proto.CompactTextString(m) }
func (*DatabaseV2) ProtoMessage()    {}
func (*DatabaseV2) Descriptor() ([]byte, []int) {
	return fileDescriptor_f393e68fe5690326, []int{3}
}

func (m *DatabaseV2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DatabaseV2.Unmarshal(m, b)
}
func (m *DatabaseV2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DatabaseV2.Marshal(b, m, deterministic)
}
func (m *DatabaseV2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DatabaseV2.Merge(m, src)
}
func (m *DatabaseV2) XXX_Size() int {
	return xxx_messageInfo_DatabaseV2.Size(m)
}
func (m *DatabaseV2) XXX_DiscardUnknown() {
	xxx_messageInfo_DatabaseV2.DiscardUnknown(m)
}

var xxx_messageInfo_DatabaseV2 proto.InternalMessageInfo

func (m *DatabaseV2) GetDbName() string {
	if m != nil {
		return m.DbName
	}
	return ""
}

func (m *DatabaseV2) GetTables() []*TableV2 {
	if m != nil {
		return m.Tables
	}
	return nil
}

type TableMeta struct {
	OrgId                string        `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Remark               string        `protobuf:"bytes,2,opt,name=remark,proto3" json:"remark,omitempty"`
	Dbs                  []*DatabaseV2 `protobuf:"bytes,3,rep,name=dbs,proto3" json:"dbs,omitempty"`
	Timestamp            uint64        `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *TableMeta) Reset()         { *m = TableMeta{} }
func (m *TableMeta) String() string { return proto.CompactTextString(m) }
func (*TableMeta) ProtoMessage()    {}
func (*TableMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_f393e68fe5690326, []int{4}
}

func (m *TableMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TableMeta.Unmarshal(m, b)
}
func (m *TableMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TableMeta.Marshal(b, m, deterministic)
}
func (m *TableMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TableMeta.Merge(m, src)
}
func (m *TableMeta) XXX_Size() int {
	return xxx_messageInfo_TableMeta.Size(m)
}
func (m *TableMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_TableMeta.DiscardUnknown(m)
}

var xxx_messageInfo_TableMeta proto.InternalMessageInfo

func (m *TableMeta) GetOrgId() string {
	if m != nil {
		return m.OrgId
	}
	return ""
}

func (m *TableMeta) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *TableMeta) GetDbs() []*DatabaseV2 {
	if m != nil {
		return m.Dbs
	}
	return nil
}

func (m *TableMeta) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type AuthorityMeta struct {
	OwnerOrgId           string   `protobuf:"bytes,1,opt,name=owner_org_id,json=ownerOrgId,proto3" json:"owner_org_id,omitempty"`
	PeriodOfValidate     int64    `protobuf:"varint,2,opt,name=period_of_validate,json=periodOfValidate,proto3" json:"period_of_validate,omitempty"`
	Remark               string   `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`
	Timestamp            uint64   `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthorityMeta) Reset()         { *m = AuthorityMeta{} }
func (m *AuthorityMeta) String() string { return proto.CompactTextString(m) }
func (*AuthorityMeta) ProtoMessage()    {}
func (*AuthorityMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_f393e68fe5690326, []int{5}
}

func (m *AuthorityMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthorityMeta.Unmarshal(m, b)
}
func (m *AuthorityMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthorityMeta.Marshal(b, m, deterministic)
}
func (m *AuthorityMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthorityMeta.Merge(m, src)
}
func (m *AuthorityMeta) XXX_Size() int {
	return xxx_messageInfo_AuthorityMeta.Size(m)
}
func (m *AuthorityMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthorityMeta.DiscardUnknown(m)
}

var xxx_messageInfo_AuthorityMeta proto.InternalMessageInfo

func (m *AuthorityMeta) GetOwnerOrgId() string {
	if m != nil {
		return m.OwnerOrgId
	}
	return ""
}

func (m *AuthorityMeta) GetPeriodOfValidate() int64 {
	if m != nil {
		return m.PeriodOfValidate
	}
	return 0
}

func (m *AuthorityMeta) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *AuthorityMeta) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type DataV2 struct {
	Payload              []byte   `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataV2) Reset()         { *m = DataV2{} }
func (m *DataV2) String() string { return proto.CompactTextString(m) }
func (*DataV2) ProtoMessage()    {}
func (*DataV2) Descriptor() ([]byte, []int) {
	return fileDescriptor_f393e68fe5690326, []int{6}
}

func (m *DataV2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataV2.Unmarshal(m, b)
}
func (m *DataV2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataV2.Marshal(b, m, deterministic)
}
func (m *DataV2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataV2.Merge(m, src)
}
func (m *DataV2) XXX_Size() int {
	return xxx_messageInfo_DataV2.Size(m)
}
func (m *DataV2) XXX_DiscardUnknown() {
	xxx_messageInfo_DataV2.DiscardUnknown(m)
}

var xxx_messageInfo_DataV2 proto.InternalMessageInfo

func (m *DataV2) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *DataV2) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func init() {
	proto.RegisterType((*FileV2)(nil), "adopter.FileV2")
	proto.RegisterType((*FileMeta)(nil), "adopter.FileMeta")
	proto.RegisterType((*TableV2)(nil), "adopter.TableV2")
	proto.RegisterType((*DatabaseV2)(nil), "adopter.DatabaseV2")
	proto.RegisterType((*TableMeta)(nil), "adopter.TableMeta")
	proto.RegisterType((*AuthorityMeta)(nil), "adopter.AuthorityMeta")
	proto.RegisterType((*DataV2)(nil), "adopter.DataV2")
}

func init() { proto.RegisterFile("adopter-v2.proto", fileDescriptor_f393e68fe5690326) }

var fileDescriptor_f393e68fe5690326 = []byte{
	// 403 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0xc1, 0xaa, 0xd3, 0x40,
	0x14, 0x86, 0xc9, 0x4d, 0x6f, 0x72, 0x73, 0xec, 0xc5, 0x32, 0xa2, 0x06, 0x54, 0x08, 0x01, 0x21,
	0x0b, 0xed, 0x22, 0x6e, 0xdd, 0x08, 0x22, 0xba, 0xd0, 0xc2, 0x28, 0xdd, 0xb8, 0x08, 0x27, 0xcc,
	0xb4, 0x19, 0x4c, 0x3a, 0x61, 0x66, 0xac, 0xdc, 0x2e, 0xf4, 0x29, 0x7c, 0x5f, 0x99, 0xc9, 0x24,
	0x4d, 0x37, 0x0a, 0xee, 0x32, 0xff, 0x07, 0xe7, 0xfc, 0xdf, 0x81, 0xc0, 0x0a, 0x99, 0xec, 0x0d,
	0x57, 0x2f, 0x8f, 0xe5, 0xba, 0x57, 0xd2, 0x48, 0x12, 0xfb, 0x24, 0xd7, 0x10, 0xbd, 0x13, 0x2d,
	0xdf, 0x96, 0xe4, 0x09, 0x24, 0x3b, 0xd1, 0xf2, 0xea, 0x80, 0x1d, 0x4f, 0x83, 0x2c, 0x28, 0x12,
	0x7a, 0x63, 0x83, 0x4f, 0xd8, 0xf1, 0x09, 0x36, 0xa8, 0x9b, 0xf4, 0xea, 0x0c, 0xdf, 0xa3, 0x6e,
	0x26, 0xa8, 0xc5, 0x89, 0xa7, 0x61, 0x16, 0x14, 0xb7, 0x03, 0xfc, 0x2c, 0x4e, 0x9c, 0x10, 0x58,
	0xb4, 0x72, 0xaf, 0xd3, 0x45, 0x16, 0x14, 0x4b, 0xea, 0xbe, 0xf3, 0x9f, 0x70, 0x63, 0x97, 0x7e,
	0xe4, 0x06, 0xc9, 0x43, 0x88, 0xa4, 0xda, 0x57, 0x82, 0xf9, 0x9d, 0xd7, 0x52, 0xed, 0x3f, 0x30,
	0xf2, 0x08, 0x22, 0xc5, 0x3b, 0x54, 0xdf, 0xfc, 0x36, 0xff, 0x22, 0xcf, 0xe1, 0xda, 0x8e, 0xd6,
	0x69, 0x98, 0x85, 0xc5, 0xbd, 0xf2, 0xfe, 0xda, 0x8b, 0xac, 0x07, 0x0b, 0x3a, 0x50, 0xf2, 0x14,
	0x12, 0x23, 0x3a, 0xae, 0x0d, 0x76, 0xbd, 0x5b, 0xbd, 0xa0, 0xe7, 0x20, 0xff, 0x0a, 0xf1, 0x17,
	0xac, 0x9d, 0xf5, 0x33, 0x00, 0x63, 0x3f, 0xe7, 0xda, 0x89, 0x4b, 0x9c, 0xf7, 0x84, 0x67, 0xe2,
	0x03, 0x76, 0xe6, 0xa3, 0x5c, 0x38, 0x93, 0xdb, 0x00, 0xbc, 0x45, 0x83, 0x35, 0x6a, 0x3b, 0xff,
	0x31, 0xc4, 0xac, 0x9e, 0x0f, 0x8f, 0x58, 0xed, 0x26, 0x17, 0x10, 0xb9, 0x39, 0x3a, 0xbd, 0x72,
	0x26, 0xab, 0xc9, 0xc4, 0x57, 0xa3, 0x9e, 0xe7, 0xbf, 0x20, 0x71, 0xd1, 0xff, 0x9d, 0x2b, 0x64,
	0xf5, 0x78, 0xac, 0x07, 0xd3, 0x8a, 0x73, 0x41, 0x6a, 0xf9, 0x3f, 0xce, 0xf5, 0x3b, 0x80, 0xdb,
	0x37, 0xdf, 0x4d, 0x23, 0x95, 0x30, 0x77, 0xae, 0x45, 0x06, 0x4b, 0xf9, 0xe3, 0xc0, 0x55, 0x75,
	0xd1, 0x05, 0x5c, 0xb6, 0x71, 0x85, 0x5e, 0x00, 0xe9, 0xb9, 0x12, 0x92, 0x55, 0x72, 0x57, 0x1d,
	0xb1, 0x15, 0x0c, 0x0d, 0x77, 0xe5, 0x42, 0xba, 0x1a, 0xc8, 0x66, 0xb7, 0xf5, 0xf9, 0xac, 0x7e,
	0x78, 0x51, 0xff, 0xef, 0xbd, 0x5e, 0x43, 0x64, 0x45, 0xb6, 0x25, 0x49, 0x21, 0xee, 0xf1, 0xae,
	0x95, 0x38, 0x54, 0x59, 0xd2, 0xf1, 0x69, 0xc9, 0x91, 0x2b, 0x2d, 0xe4, 0xc1, 0x5f, 0x66, 0x7c,
	0xd6, 0x91, 0xfb, 0x13, 0x5e, 0xfd, 0x09, 0x00, 0x00, 0xff, 0xff, 0xba, 0x5e, 0xb1, 0xc5, 0x1d,
	0x03, 0x00, 0x00,
}
