// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api-v2.proto

package adopter

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SetResourceRequest struct {
	Payload              []byte   `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Commit               string   `protobuf:"bytes,2,opt,name=commit,proto3" json:"commit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetResourceRequest) Reset()         { *m = SetResourceRequest{} }
func (m *SetResourceRequest) String() string { return proto.CompactTextString(m) }
func (*SetResourceRequest) ProtoMessage()    {}
func (*SetResourceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dead8d96438b57e0, []int{0}
}

func (m *SetResourceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetResourceRequest.Unmarshal(m, b)
}
func (m *SetResourceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetResourceRequest.Marshal(b, m, deterministic)
}
func (m *SetResourceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetResourceRequest.Merge(m, src)
}
func (m *SetResourceRequest) XXX_Size() int {
	return xxx_messageInfo_SetResourceRequest.Size(m)
}
func (m *SetResourceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetResourceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetResourceRequest proto.InternalMessageInfo

func (m *SetResourceRequest) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *SetResourceRequest) GetCommit() string {
	if m != nil {
		return m.Commit
	}
	return ""
}

type SetAuthorityRequest struct {
	Payload              []byte   `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	AuthOrgId            string   `protobuf:"bytes,2,opt,name=auth_org_id,json=authOrgId,proto3" json:"auth_org_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetAuthorityRequest) Reset()         { *m = SetAuthorityRequest{} }
func (m *SetAuthorityRequest) String() string { return proto.CompactTextString(m) }
func (*SetAuthorityRequest) ProtoMessage()    {}
func (*SetAuthorityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dead8d96438b57e0, []int{1}
}

func (m *SetAuthorityRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetAuthorityRequest.Unmarshal(m, b)
}
func (m *SetAuthorityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetAuthorityRequest.Marshal(b, m, deterministic)
}
func (m *SetAuthorityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetAuthorityRequest.Merge(m, src)
}
func (m *SetAuthorityRequest) XXX_Size() int {
	return xxx_messageInfo_SetAuthorityRequest.Size(m)
}
func (m *SetAuthorityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetAuthorityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetAuthorityRequest proto.InternalMessageInfo

func (m *SetAuthorityRequest) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *SetAuthorityRequest) GetAuthOrgId() string {
	if m != nil {
		return m.AuthOrgId
	}
	return ""
}

func init() {
	proto.RegisterType((*SetResourceRequest)(nil), "adopter.SetResourceRequest")
	proto.RegisterType((*SetAuthorityRequest)(nil), "adopter.SetAuthorityRequest")
}

func init() { proto.RegisterFile("api-v2.proto", fileDescriptor_dead8d96438b57e0) }

var fileDescriptor_dead8d96438b57e0 = []byte{
	// 155 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0x2c, 0xc8, 0xd4,
	0x2d, 0x33, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4f, 0x4c, 0xc9, 0x2f, 0x28, 0x49,
	0x2d, 0x52, 0x72, 0xe3, 0x12, 0x0a, 0x4e, 0x2d, 0x09, 0x4a, 0x2d, 0xce, 0x2f, 0x2d, 0x4a, 0x4e,
	0x0d, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x92, 0xe0, 0x62, 0x2f, 0x48, 0xac, 0xcc, 0xc9,
	0x4f, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x09, 0x82, 0x71, 0x85, 0xc4, 0xb8, 0xd8, 0x92,
	0xf3, 0x73, 0x73, 0x33, 0x4b, 0x24, 0x98, 0x14, 0x18, 0x35, 0x38, 0x83, 0xa0, 0x3c, 0x25, 0x7f,
	0x2e, 0xe1, 0xe0, 0xd4, 0x12, 0xc7, 0xd2, 0x92, 0x8c, 0xfc, 0xa2, 0xcc, 0x92, 0x4a, 0xc2, 0x06,
	0xc9, 0x71, 0x71, 0x27, 0x96, 0x96, 0x64, 0xc4, 0xe7, 0x17, 0xa5, 0xc7, 0x67, 0xa6, 0x40, 0x4d,
	0xe3, 0x04, 0x09, 0xf9, 0x17, 0xa5, 0x7b, 0xa6, 0x24, 0xb1, 0x81, 0x1d, 0x6a, 0x0c, 0x08, 0x00,
	0x00, 0xff, 0xff, 0xcc, 0xdc, 0x87, 0xd6, 0xb8, 0x00, 0x00, 0x00,
}
