// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lottery.proto

package lottery

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 参与者
type Participator struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Word                 string   `protobuf:"bytes,3,opt,name=word,proto3" json:"word,omitempty"`
	Time                 string   `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
	LotteryCode          string   `protobuf:"bytes,5,opt,name=lottery_code,json=lotteryCode,proto3" json:"lottery_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Participator) Reset()         { *m = Participator{} }
func (m *Participator) String() string { return proto.CompactTextString(m) }
func (*Participator) ProtoMessage()    {}
func (*Participator) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cce7afd61783b10, []int{0}
}

func (m *Participator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Participator.Unmarshal(m, b)
}
func (m *Participator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Participator.Marshal(b, m, deterministic)
}
func (m *Participator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Participator.Merge(m, src)
}
func (m *Participator) XXX_Size() int {
	return xxx_messageInfo_Participator.Size(m)
}
func (m *Participator) XXX_DiscardUnknown() {
	xxx_messageInfo_Participator.DiscardUnknown(m)
}

var xxx_messageInfo_Participator proto.InternalMessageInfo

func (m *Participator) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Participator) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Participator) GetWord() string {
	if m != nil {
		return m.Word
	}
	return ""
}

func (m *Participator) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *Participator) GetLotteryCode() string {
	if m != nil {
		return m.LotteryCode
	}
	return ""
}

// 抽奖池参与者信息
type PartyLottery struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	LotteryCode          string   `protobuf:"bytes,2,opt,name=lottery_code,json=lotteryCode,proto3" json:"lottery_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PartyLottery) Reset()         { *m = PartyLottery{} }
func (m *PartyLottery) String() string { return proto.CompactTextString(m) }
func (*PartyLottery) ProtoMessage()    {}
func (*PartyLottery) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cce7afd61783b10, []int{1}
}

func (m *PartyLottery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PartyLottery.Unmarshal(m, b)
}
func (m *PartyLottery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PartyLottery.Marshal(b, m, deterministic)
}
func (m *PartyLottery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PartyLottery.Merge(m, src)
}
func (m *PartyLottery) XXX_Size() int {
	return xxx_messageInfo_PartyLottery.Size(m)
}
func (m *PartyLottery) XXX_DiscardUnknown() {
	xxx_messageInfo_PartyLottery.DiscardUnknown(m)
}

var xxx_messageInfo_PartyLottery proto.InternalMessageInfo

func (m *PartyLottery) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PartyLottery) GetLotteryCode() string {
	if m != nil {
		return m.LotteryCode
	}
	return ""
}

// 中奖信息
type WinLottery struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	LotteryCode          string   `protobuf:"bytes,2,opt,name=lottery_code,json=lotteryCode,proto3" json:"lottery_code,omitempty"`
	WinWord              string   `protobuf:"bytes,3,opt,name=win_word,json=winWord,proto3" json:"win_word,omitempty"`
	WinCode              string   `protobuf:"bytes,4,opt,name=win_code,json=winCode,proto3" json:"win_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WinLottery) Reset()         { *m = WinLottery{} }
func (m *WinLottery) String() string { return proto.CompactTextString(m) }
func (*WinLottery) ProtoMessage()    {}
func (*WinLottery) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cce7afd61783b10, []int{2}
}

func (m *WinLottery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WinLottery.Unmarshal(m, b)
}
func (m *WinLottery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WinLottery.Marshal(b, m, deterministic)
}
func (m *WinLottery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WinLottery.Merge(m, src)
}
func (m *WinLottery) XXX_Size() int {
	return xxx_messageInfo_WinLottery.Size(m)
}
func (m *WinLottery) XXX_DiscardUnknown() {
	xxx_messageInfo_WinLottery.DiscardUnknown(m)
}

var xxx_messageInfo_WinLottery proto.InternalMessageInfo

func (m *WinLottery) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *WinLottery) GetLotteryCode() string {
	if m != nil {
		return m.LotteryCode
	}
	return ""
}

func (m *WinLottery) GetWinWord() string {
	if m != nil {
		return m.WinWord
	}
	return ""
}

func (m *WinLottery) GetWinCode() string {
	if m != nil {
		return m.WinCode
	}
	return ""
}

type ListOfString struct {
	Value                []string `protobuf:"bytes,1,rep,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListOfString) Reset()         { *m = ListOfString{} }
func (m *ListOfString) String() string { return proto.CompactTextString(m) }
func (*ListOfString) ProtoMessage()    {}
func (*ListOfString) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cce7afd61783b10, []int{3}
}

func (m *ListOfString) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListOfString.Unmarshal(m, b)
}
func (m *ListOfString) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListOfString.Marshal(b, m, deterministic)
}
func (m *ListOfString) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOfString.Merge(m, src)
}
func (m *ListOfString) XXX_Size() int {
	return xxx_messageInfo_ListOfString.Size(m)
}
func (m *ListOfString) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOfString.DiscardUnknown(m)
}

var xxx_messageInfo_ListOfString proto.InternalMessageInfo

func (m *ListOfString) GetValue() []string {
	if m != nil {
		return m.Value
	}
	return nil
}

type ListOfRound struct {
	Round                []*ListOfString `protobuf:"bytes,1,rep,name=round,proto3" json:"round,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ListOfRound) Reset()         { *m = ListOfRound{} }
func (m *ListOfRound) String() string { return proto.CompactTextString(m) }
func (*ListOfRound) ProtoMessage()    {}
func (*ListOfRound) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cce7afd61783b10, []int{4}
}

func (m *ListOfRound) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListOfRound.Unmarshal(m, b)
}
func (m *ListOfRound) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListOfRound.Marshal(b, m, deterministic)
}
func (m *ListOfRound) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOfRound.Merge(m, src)
}
func (m *ListOfRound) XXX_Size() int {
	return xxx_messageInfo_ListOfRound.Size(m)
}
func (m *ListOfRound) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOfRound.DiscardUnknown(m)
}

var xxx_messageInfo_ListOfRound proto.InternalMessageInfo

func (m *ListOfRound) GetRound() []*ListOfString {
	if m != nil {
		return m.Round
	}
	return nil
}

// 单场抽奖数组
type LotteryData struct {
	Parties              map[string]*PartyLottery `protobuf:"bytes,1,rep,name=parties,proto3" json:"parties,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	PriorityParties      map[string]*ListOfRound  `protobuf:"bytes,2,rep,name=priority_parties,json=priorityParties,proto3" json:"priority_parties,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	WinLottery           map[string]*WinLottery   `protobuf:"bytes,3,rep,name=win_lottery,json=winLottery,proto3" json:"win_lottery,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *LotteryData) Reset()         { *m = LotteryData{} }
func (m *LotteryData) String() string { return proto.CompactTextString(m) }
func (*LotteryData) ProtoMessage()    {}
func (*LotteryData) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cce7afd61783b10, []int{5}
}

func (m *LotteryData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LotteryData.Unmarshal(m, b)
}
func (m *LotteryData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LotteryData.Marshal(b, m, deterministic)
}
func (m *LotteryData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LotteryData.Merge(m, src)
}
func (m *LotteryData) XXX_Size() int {
	return xxx_messageInfo_LotteryData.Size(m)
}
func (m *LotteryData) XXX_DiscardUnknown() {
	xxx_messageInfo_LotteryData.DiscardUnknown(m)
}

var xxx_messageInfo_LotteryData proto.InternalMessageInfo

func (m *LotteryData) GetParties() map[string]*PartyLottery {
	if m != nil {
		return m.Parties
	}
	return nil
}

func (m *LotteryData) GetPriorityParties() map[string]*ListOfRound {
	if m != nil {
		return m.PriorityParties
	}
	return nil
}

func (m *LotteryData) GetWinLottery() map[string]*WinLottery {
	if m != nil {
		return m.WinLottery
	}
	return nil
}

// 单场单轮单次的抽奖结果记录
type LotteryRecord struct {
	WinWord              string    `protobuf:"bytes,1,opt,name=win_word,json=winWord,proto3" json:"win_word,omitempty"`
	WinCode              string    `protobuf:"bytes,2,opt,name=win_code,json=winCode,proto3" json:"win_code,omitempty"`
	SortCode             []string  `protobuf:"bytes,3,rep,name=sort_code,json=sortCode,proto3" json:"sort_code,omitempty"`
	SortValue            []float64 `protobuf:"fixed64,4,rep,packed,name=sort_value,json=sortValue,proto3" json:"sort_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LotteryRecord) Reset()         { *m = LotteryRecord{} }
func (m *LotteryRecord) String() string { return proto.CompactTextString(m) }
func (*LotteryRecord) ProtoMessage()    {}
func (*LotteryRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cce7afd61783b10, []int{6}
}

func (m *LotteryRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LotteryRecord.Unmarshal(m, b)
}
func (m *LotteryRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LotteryRecord.Marshal(b, m, deterministic)
}
func (m *LotteryRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LotteryRecord.Merge(m, src)
}
func (m *LotteryRecord) XXX_Size() int {
	return xxx_messageInfo_LotteryRecord.Size(m)
}
func (m *LotteryRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_LotteryRecord.DiscardUnknown(m)
}

var xxx_messageInfo_LotteryRecord proto.InternalMessageInfo

func (m *LotteryRecord) GetWinWord() string {
	if m != nil {
		return m.WinWord
	}
	return ""
}

func (m *LotteryRecord) GetWinCode() string {
	if m != nil {
		return m.WinCode
	}
	return ""
}

func (m *LotteryRecord) GetSortCode() []string {
	if m != nil {
		return m.SortCode
	}
	return nil
}

func (m *LotteryRecord) GetSortValue() []float64 {
	if m != nil {
		return m.SortValue
	}
	return nil
}

// 抽奖过程
type LotteryHistory struct {
	LotteryHistory       []*LotteryRecord `protobuf:"bytes,1,rep,name=lottery_history,json=lotteryHistory,proto3" json:"lottery_history,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *LotteryHistory) Reset()         { *m = LotteryHistory{} }
func (m *LotteryHistory) String() string { return proto.CompactTextString(m) }
func (*LotteryHistory) ProtoMessage()    {}
func (*LotteryHistory) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cce7afd61783b10, []int{7}
}

func (m *LotteryHistory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LotteryHistory.Unmarshal(m, b)
}
func (m *LotteryHistory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LotteryHistory.Marshal(b, m, deterministic)
}
func (m *LotteryHistory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LotteryHistory.Merge(m, src)
}
func (m *LotteryHistory) XXX_Size() int {
	return xxx_messageInfo_LotteryHistory.Size(m)
}
func (m *LotteryHistory) XXX_DiscardUnknown() {
	xxx_messageInfo_LotteryHistory.DiscardUnknown(m)
}

var xxx_messageInfo_LotteryHistory proto.InternalMessageInfo

func (m *LotteryHistory) GetLotteryHistory() []*LotteryRecord {
	if m != nil {
		return m.LotteryHistory
	}
	return nil
}

type PartyKV struct {
	Key                  string        `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                *PartyLottery `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *PartyKV) Reset()         { *m = PartyKV{} }
func (m *PartyKV) String() string { return proto.CompactTextString(m) }
func (*PartyKV) ProtoMessage()    {}
func (*PartyKV) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cce7afd61783b10, []int{8}
}

func (m *PartyKV) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PartyKV.Unmarshal(m, b)
}
func (m *PartyKV) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PartyKV.Marshal(b, m, deterministic)
}
func (m *PartyKV) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PartyKV.Merge(m, src)
}
func (m *PartyKV) XXX_Size() int {
	return xxx_messageInfo_PartyKV.Size(m)
}
func (m *PartyKV) XXX_DiscardUnknown() {
	xxx_messageInfo_PartyKV.DiscardUnknown(m)
}

var xxx_messageInfo_PartyKV proto.InternalMessageInfo

func (m *PartyKV) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *PartyKV) GetValue() *PartyLottery {
	if m != nil {
		return m.Value
	}
	return nil
}

type PriorityPartyKV struct {
	Key                  string       `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                *ListOfRound `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *PriorityPartyKV) Reset()         { *m = PriorityPartyKV{} }
func (m *PriorityPartyKV) String() string { return proto.CompactTextString(m) }
func (*PriorityPartyKV) ProtoMessage()    {}
func (*PriorityPartyKV) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cce7afd61783b10, []int{9}
}

func (m *PriorityPartyKV) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PriorityPartyKV.Unmarshal(m, b)
}
func (m *PriorityPartyKV) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PriorityPartyKV.Marshal(b, m, deterministic)
}
func (m *PriorityPartyKV) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PriorityPartyKV.Merge(m, src)
}
func (m *PriorityPartyKV) XXX_Size() int {
	return xxx_messageInfo_PriorityPartyKV.Size(m)
}
func (m *PriorityPartyKV) XXX_DiscardUnknown() {
	xxx_messageInfo_PriorityPartyKV.DiscardUnknown(m)
}

var xxx_messageInfo_PriorityPartyKV proto.InternalMessageInfo

func (m *PriorityPartyKV) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *PriorityPartyKV) GetValue() *ListOfRound {
	if m != nil {
		return m.Value
	}
	return nil
}

type WinLotteryKV struct {
	Key                  string      `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                *WinLottery `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *WinLotteryKV) Reset()         { *m = WinLotteryKV{} }
func (m *WinLotteryKV) String() string { return proto.CompactTextString(m) }
func (*WinLotteryKV) ProtoMessage()    {}
func (*WinLotteryKV) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cce7afd61783b10, []int{10}
}

func (m *WinLotteryKV) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WinLotteryKV.Unmarshal(m, b)
}
func (m *WinLotteryKV) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WinLotteryKV.Marshal(b, m, deterministic)
}
func (m *WinLotteryKV) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WinLotteryKV.Merge(m, src)
}
func (m *WinLotteryKV) XXX_Size() int {
	return xxx_messageInfo_WinLotteryKV.Size(m)
}
func (m *WinLotteryKV) XXX_DiscardUnknown() {
	xxx_messageInfo_WinLotteryKV.DiscardUnknown(m)
}

var xxx_messageInfo_WinLotteryKV proto.InternalMessageInfo

func (m *WinLotteryKV) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *WinLotteryKV) GetValue() *WinLottery {
	if m != nil {
		return m.Value
	}
	return nil
}

type LotteryStoreData struct {
	Parties              []*PartyKV         `protobuf:"bytes,1,rep,name=parties,proto3" json:"parties,omitempty"`
	PriorityParties      []*PriorityPartyKV `protobuf:"bytes,2,rep,name=priority_parties,json=priorityParties,proto3" json:"priority_parties,omitempty"`
	WinLottery           []*WinLotteryKV    `protobuf:"bytes,3,rep,name=win_lottery,json=winLottery,proto3" json:"win_lottery,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *LotteryStoreData) Reset()         { *m = LotteryStoreData{} }
func (m *LotteryStoreData) String() string { return proto.CompactTextString(m) }
func (*LotteryStoreData) ProtoMessage()    {}
func (*LotteryStoreData) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cce7afd61783b10, []int{11}
}

func (m *LotteryStoreData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LotteryStoreData.Unmarshal(m, b)
}
func (m *LotteryStoreData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LotteryStoreData.Marshal(b, m, deterministic)
}
func (m *LotteryStoreData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LotteryStoreData.Merge(m, src)
}
func (m *LotteryStoreData) XXX_Size() int {
	return xxx_messageInfo_LotteryStoreData.Size(m)
}
func (m *LotteryStoreData) XXX_DiscardUnknown() {
	xxx_messageInfo_LotteryStoreData.DiscardUnknown(m)
}

var xxx_messageInfo_LotteryStoreData proto.InternalMessageInfo

func (m *LotteryStoreData) GetParties() []*PartyKV {
	if m != nil {
		return m.Parties
	}
	return nil
}

func (m *LotteryStoreData) GetPriorityParties() []*PriorityPartyKV {
	if m != nil {
		return m.PriorityParties
	}
	return nil
}

func (m *LotteryStoreData) GetWinLottery() []*WinLotteryKV {
	if m != nil {
		return m.WinLottery
	}
	return nil
}

func init() {
	proto.RegisterType((*Participator)(nil), "lottery.Participator")
	proto.RegisterType((*PartyLottery)(nil), "lottery.PartyLottery")
	proto.RegisterType((*WinLottery)(nil), "lottery.WinLottery")
	proto.RegisterType((*ListOfString)(nil), "lottery.ListOfString")
	proto.RegisterType((*ListOfRound)(nil), "lottery.ListOfRound")
	proto.RegisterType((*LotteryData)(nil), "lottery.LotteryData")
	proto.RegisterMapType((map[string]*PartyLottery)(nil), "lottery.LotteryData.PartiesEntry")
	proto.RegisterMapType((map[string]*ListOfRound)(nil), "lottery.LotteryData.PriorityPartiesEntry")
	proto.RegisterMapType((map[string]*WinLottery)(nil), "lottery.LotteryData.WinLotteryEntry")
	proto.RegisterType((*LotteryRecord)(nil), "lottery.LotteryRecord")
	proto.RegisterType((*LotteryHistory)(nil), "lottery.LotteryHistory")
	proto.RegisterType((*PartyKV)(nil), "lottery.PartyKV")
	proto.RegisterType((*PriorityPartyKV)(nil), "lottery.PriorityPartyKV")
	proto.RegisterType((*WinLotteryKV)(nil), "lottery.WinLotteryKV")
	proto.RegisterType((*LotteryStoreData)(nil), "lottery.LotteryStoreData")
}

func init() { proto.RegisterFile("lottery.proto", fileDescriptor_2cce7afd61783b10) }

var fileDescriptor_2cce7afd61783b10 = []byte{
	// 564 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x95, 0xdd, 0x6a, 0xdb, 0x30,
	0x14, 0xc7, 0xb1, 0x9d, 0x2c, 0xcd, 0x71, 0x9a, 0x04, 0x2d, 0x1d, 0x5e, 0xc7, 0x20, 0x35, 0xbd,
	0x48, 0x3b, 0xc8, 0xc5, 0x06, 0x63, 0x74, 0x17, 0x63, 0x74, 0x85, 0x42, 0x0a, 0x6d, 0xdd, 0x91,
	0xee, 0x2e, 0x78, 0xb1, 0xb6, 0x89, 0xa5, 0x96, 0x51, 0x94, 0x05, 0x5f, 0xec, 0x62, 0xcf, 0xb5,
	0x17, 0xda, 0x63, 0x0c, 0x1d, 0xc9, 0xf1, 0x47, 0x5c, 0xd8, 0xc7, 0x9d, 0xfc, 0xd7, 0x39, 0x3f,
	0xe9, 0xe8, 0x7f, 0x0e, 0x86, 0xdd, 0x05, 0x97, 0x92, 0x8a, 0x74, 0x9c, 0x08, 0x2e, 0x39, 0x69,
	0x99, 0x4f, 0xff, 0x3b, 0x74, 0xae, 0x42, 0x21, 0xd9, 0x9c, 0x25, 0xa1, 0xe4, 0x82, 0x74, 0xc1,
	0x66, 0x91, 0x67, 0x0d, 0xad, 0x51, 0x3b, 0xb0, 0x59, 0x44, 0x08, 0x34, 0xe2, 0xf0, 0x8e, 0x7a,
	0x36, 0x2a, 0xb8, 0x56, 0xda, 0x9a, 0x8b, 0xc8, 0x73, 0xb4, 0xa6, 0xd6, 0x4a, 0x93, 0xec, 0x8e,
	0x7a, 0x0d, 0xad, 0xa9, 0x35, 0x39, 0x80, 0x8e, 0x39, 0x66, 0x36, 0xe7, 0x11, 0xf5, 0x9a, 0xb8,
	0xe7, 0x1a, 0xed, 0x94, 0x47, 0xd4, 0x7f, 0xab, 0x8f, 0x4f, 0x2f, 0xb4, 0xb6, 0x75, 0x7c, 0x15,
	0x61, 0x6f, 0x23, 0x56, 0x00, 0xb7, 0x2c, 0xfe, 0x77, 0x00, 0x79, 0x0c, 0x3b, 0x6b, 0x16, 0xcf,
	0x0a, 0x25, 0xb5, 0xd6, 0x2c, 0xbe, 0x55, 0x55, 0x99, 0x2d, 0xcc, 0x6c, 0x6c, 0xb6, 0xf0, 0xd8,
	0x43, 0xe8, 0x5c, 0xb0, 0xa5, 0xbc, 0xfc, 0x74, 0x23, 0x05, 0x8b, 0x3f, 0x93, 0x01, 0x34, 0xbf,
	0x85, 0x8b, 0x15, 0xf5, 0xac, 0xa1, 0x33, 0x6a, 0x07, 0xfa, 0xc3, 0x3f, 0x01, 0x57, 0x47, 0x05,
	0x7c, 0x15, 0x47, 0xe4, 0x19, 0x34, 0x85, 0x5a, 0x60, 0x90, 0xfb, 0x7c, 0x6f, 0x9c, 0xb9, 0x52,
	0x44, 0x05, 0x3a, 0xc6, 0xff, 0xe5, 0x80, 0x6b, 0xca, 0x7a, 0x17, 0xca, 0x90, 0xbc, 0x86, 0x56,
	0xa2, 0xac, 0xa2, 0x4b, 0x93, 0x7e, 0x90, 0xa7, 0xe7, 0x61, 0xe3, 0x2b, 0x1d, 0x73, 0x16, 0x4b,
	0x91, 0x06, 0x59, 0x06, 0x79, 0x0f, 0xfd, 0x44, 0x30, 0x2e, 0x98, 0x4c, 0x67, 0x19, 0xc5, 0x46,
	0xca, 0x51, 0x3d, 0xc5, 0x04, 0x97, 0x68, 0xbd, 0xa4, 0xac, 0x92, 0x33, 0x70, 0xd5, 0xfb, 0x18,
	0x80, 0xe7, 0x20, 0xf0, 0xb0, 0x16, 0x98, 0x7b, 0xa4, 0x59, 0xb0, 0xde, 0x08, 0xfb, 0xd7, 0xa6,
	0x09, 0xcd, 0x39, 0xa4, 0x0f, 0xce, 0x57, 0x9a, 0x1a, 0x17, 0xd5, 0x52, 0x3d, 0x9c, 0x7e, 0x5d,
	0xe5, 0x5f, 0xf1, 0xe1, 0x8a, 0xdd, 0x63, 0x1e, 0xfd, 0xc4, 0x7e, 0x65, 0xed, 0x7f, 0x80, 0x41,
	0x5d, 0x09, 0x35, 0xe8, 0xe3, 0x32, 0x7a, 0x50, 0xf1, 0x04, 0x8d, 0x2b, 0x92, 0x03, 0xe8, 0x55,
	0x6a, 0xa9, 0x81, 0x1e, 0x95, 0xa1, 0x0f, 0x37, 0xd0, 0x3c, 0xb5, 0xc0, 0xf4, 0x7f, 0x58, 0xb0,
	0x9b, 0xc9, 0x74, 0x5e, 0xe8, 0x3c, 0x6c, 0x4a, 0xeb, 0xfe, 0xa6, 0xb4, 0x4b, 0x4d, 0x49, 0x9e,
	0x40, 0x7b, 0xc9, 0x85, 0xd4, 0x7b, 0x0e, 0x36, 0xe2, 0x8e, 0x12, 0x70, 0xf3, 0x29, 0x00, 0x6e,
	0xea, 0x8b, 0x35, 0x86, 0xce, 0xc8, 0x0a, 0x30, 0x7c, 0x8a, 0xad, 0x7a, 0x0d, 0x5d, 0x73, 0x85,
	0x73, 0xb6, 0x94, 0x5c, 0xa4, 0xe4, 0x0d, 0xf4, 0xb2, 0xd9, 0xf9, 0xa2, 0x25, 0xd3, 0x78, 0x8f,
	0xaa, 0x0e, 0xeb, 0x4b, 0x07, 0xdd, 0x45, 0x09, 0xe0, 0x9f, 0x43, 0x0b, 0xfd, 0x99, 0x4c, 0xff,
	0xd3, 0x52, 0xff, 0x12, 0x7a, 0x45, 0x3b, 0xeb, 0x89, 0x7f, 0xe1, 0xa4, 0x3f, 0x81, 0x4e, 0x6e,
	0x45, 0x2d, 0xed, 0xcf, 0x2d, 0xf4, 0x7f, 0x5a, 0xd0, 0x37, 0xd2, 0x8d, 0xe4, 0x82, 0xe2, 0xb8,
	0x1e, 0x57, 0xc7, 0xb5, 0x5f, 0xae, 0x70, 0x32, 0xcd, 0xa7, 0xf3, 0xf4, 0xde, 0xe9, 0xf4, 0xf2,
	0xa4, 0x72, 0xfd, 0xdb, 0xc3, 0xf8, 0xb2, 0x6e, 0x18, 0xf7, 0x6a, 0xae, 0x3d, 0x99, 0x16, 0xa7,
	0xef, 0xe3, 0x03, 0xfc, 0x25, 0xbc, 0xf8, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x33, 0x2b, 0x56, 0x98,
	0x23, 0x06, 0x00, 0x00,
}
