// Code generated by protoc-gen-go. DO NOT EDIT.
// source: git.querycap.com/cloudchain/chaincode/protos/binary/file_stat.proto

package binary // import "git.querycap.com/cloudchain/chaincode/protos/binary"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FileStatsSets struct {
	Data                 [][]byte `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileStatsSets) Reset()         { *m = FileStatsSets{} }
func (m *FileStatsSets) String() string { return proto.CompactTextString(m) }
func (*FileStatsSets) ProtoMessage()    {}
func (*FileStatsSets) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb6a2b504080c505, []int{0}
}
func (m *FileStatsSets) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileStatsSets.Unmarshal(m, b)
}
func (m *FileStatsSets) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileStatsSets.Marshal(b, m, deterministic)
}
func (dst *FileStatsSets) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileStatsSets.Merge(dst, src)
}
func (m *FileStatsSets) XXX_Size() int {
	return xxx_messageInfo_FileStatsSets.Size(m)
}
func (m *FileStatsSets) XXX_DiscardUnknown() {
	xxx_messageInfo_FileStatsSets.DiscardUnknown(m)
}

var xxx_messageInfo_FileStatsSets proto.InternalMessageInfo

func (m *FileStatsSets) GetData() [][]byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type FileStatSet struct {
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	DataHash             string               `protobuf:"bytes,2,opt,name=data_hash,json=dataHash,proto3" json:"data_hash,omitempty"`
	Data                 [][]byte             `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *FileStatSet) Reset()         { *m = FileStatSet{} }
func (m *FileStatSet) String() string { return proto.CompactTextString(m) }
func (*FileStatSet) ProtoMessage()    {}
func (*FileStatSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb6a2b504080c505, []int{1}
}
func (m *FileStatSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileStatSet.Unmarshal(m, b)
}
func (m *FileStatSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileStatSet.Marshal(b, m, deterministic)
}
func (dst *FileStatSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileStatSet.Merge(dst, src)
}
func (m *FileStatSet) XXX_Size() int {
	return xxx_messageInfo_FileStatSet.Size(m)
}
func (m *FileStatSet) XXX_DiscardUnknown() {
	xxx_messageInfo_FileStatSet.DiscardUnknown(m)
}

var xxx_messageInfo_FileStatSet proto.InternalMessageInfo

func (m *FileStatSet) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *FileStatSet) GetDataHash() string {
	if m != nil {
		return m.DataHash
	}
	return ""
}

func (m *FileStatSet) GetData() [][]byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type FileStat struct {
	Log                  string          `protobuf:"bytes,1,opt,name=log,proto3" json:"log,omitempty"`
	HasDetail            bool            `protobuf:"varint,2,opt,name=hasDetail,proto3" json:"hasDetail,omitempty"`
	Detail               *FileStatDetail `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *FileStat) Reset()         { *m = FileStat{} }
func (m *FileStat) String() string { return proto.CompactTextString(m) }
func (*FileStat) ProtoMessage()    {}
func (*FileStat) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb6a2b504080c505, []int{2}
}
func (m *FileStat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileStat.Unmarshal(m, b)
}
func (m *FileStat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileStat.Marshal(b, m, deterministic)
}
func (dst *FileStat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileStat.Merge(dst, src)
}
func (m *FileStat) XXX_Size() int {
	return xxx_messageInfo_FileStat.Size(m)
}
func (m *FileStat) XXX_DiscardUnknown() {
	xxx_messageInfo_FileStat.DiscardUnknown(m)
}

var xxx_messageInfo_FileStat proto.InternalMessageInfo

func (m *FileStat) GetLog() string {
	if m != nil {
		return m.Log
	}
	return ""
}

func (m *FileStat) GetHasDetail() bool {
	if m != nil {
		return m.HasDetail
	}
	return false
}

func (m *FileStat) GetDetail() *FileStatDetail {
	if m != nil {
		return m.Detail
	}
	return nil
}

type FileStatDetail struct {
	Adds                 uint32   `protobuf:"varint,1,opt,name=adds,proto3" json:"adds,omitempty"`
	Updates              uint32   `protobuf:"varint,2,opt,name=updates,proto3" json:"updates,omitempty"`
	Deletes              uint32   `protobuf:"varint,3,opt,name=deletes,proto3" json:"deletes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileStatDetail) Reset()         { *m = FileStatDetail{} }
func (m *FileStatDetail) String() string { return proto.CompactTextString(m) }
func (*FileStatDetail) ProtoMessage()    {}
func (*FileStatDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb6a2b504080c505, []int{3}
}
func (m *FileStatDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileStatDetail.Unmarshal(m, b)
}
func (m *FileStatDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileStatDetail.Marshal(b, m, deterministic)
}
func (dst *FileStatDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileStatDetail.Merge(dst, src)
}
func (m *FileStatDetail) XXX_Size() int {
	return xxx_messageInfo_FileStatDetail.Size(m)
}
func (m *FileStatDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_FileStatDetail.DiscardUnknown(m)
}

var xxx_messageInfo_FileStatDetail proto.InternalMessageInfo

func (m *FileStatDetail) GetAdds() uint32 {
	if m != nil {
		return m.Adds
	}
	return 0
}

func (m *FileStatDetail) GetUpdates() uint32 {
	if m != nil {
		return m.Updates
	}
	return 0
}

func (m *FileStatDetail) GetDeletes() uint32 {
	if m != nil {
		return m.Deletes
	}
	return 0
}

func init() {
	proto.RegisterType((*FileStatsSets)(nil), "binary.FileStatsSets")
	proto.RegisterType((*FileStatSet)(nil), "binary.FileStatSet")
	proto.RegisterType((*FileStat)(nil), "binary.FileStat")
	proto.RegisterType((*FileStatDetail)(nil), "binary.FileStatDetail")
}

func init() {
	proto.RegisterFile("git.querycap.com/cloudchain/chaincode/protos/binary/file_stat.proto", fileDescriptor_fb6a2b504080c505)
}

var fileDescriptor_fb6a2b504080c505 = []byte{
	// 311 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0xc1, 0x4b, 0xf3, 0x40,
	0x10, 0xc5, 0xc9, 0x97, 0x8f, 0xda, 0x4c, 0xad, 0xc8, 0x1e, 0x24, 0x54, 0xc1, 0x52, 0x2f, 0x3d,
	0x6d, 0xc0, 0x22, 0x78, 0x56, 0x11, 0xcf, 0x5b, 0x0f, 0xe2, 0xa5, 0x4c, 0xb3, 0xdb, 0x64, 0x65,
	0xdb, 0x8d, 0xdd, 0x09, 0xd8, 0xff, 0x5e, 0xb2, 0xdb, 0x6d, 0xf5, 0xea, 0x25, 0xcc, 0xbc, 0xf7,
	0x78, 0xbf, 0x21, 0x0b, 0x8f, 0x95, 0x26, 0xfe, 0xd9, 0xaa, 0xed, 0xae, 0xc4, 0x86, 0x97, 0x76,
	0x5d, 0x94, 0xc6, 0xb6, 0xb2, 0xac, 0x51, 0x6f, 0x0a, 0xff, 0x2d, 0xad, 0x54, 0x45, 0xb3, 0xb5,
	0x64, 0x5d, 0xb1, 0xd4, 0x1b, 0xdc, 0xee, 0x8a, 0x95, 0x36, 0x6a, 0xe1, 0x08, 0x89, 0x7b, 0x9d,
	0xf5, 0x82, 0x3e, 0xba, 0xae, 0xac, 0xad, 0xcc, 0x3e, 0xbd, 0x6c, 0x57, 0x05, 0xe9, 0xb5, 0x72,
	0x84, 0xeb, 0x26, 0x04, 0x27, 0x37, 0x30, 0x7c, 0xd6, 0x46, 0xcd, 0x09, 0xc9, 0xcd, 0x15, 0x39,
	0xc6, 0xe0, 0xbf, 0x44, 0xc2, 0x3c, 0x19, 0xa7, 0xd3, 0x53, 0xe1, 0xe7, 0xc9, 0x17, 0x0c, 0x62,
	0x68, 0xae, 0x88, 0xdd, 0x43, 0x76, 0xa8, 0xc9, 0x93, 0x71, 0x32, 0x1d, 0xdc, 0x8e, 0x78, 0x00,
	0xf1, 0x08, 0xe2, 0xaf, 0x31, 0x21, 0x8e, 0x61, 0x76, 0x09, 0x59, 0x57, 0xb8, 0xa8, 0xd1, 0xd5,
	0xf9, 0xbf, 0x71, 0x32, 0xcd, 0x44, 0xbf, 0x13, 0x5e, 0xd0, 0xd5, 0x07, 0x72, 0xfa, 0x83, 0xfc,
	0x01, 0xfd, 0x48, 0x66, 0xe7, 0x90, 0x1a, 0x5b, 0x79, 0x60, 0x26, 0xba, 0x91, 0x5d, 0x41, 0x56,
	0xa3, 0x7b, 0x52, 0x84, 0xda, 0xf8, 0xba, 0xbe, 0x38, 0x0a, 0x8c, 0x43, 0x4f, 0x06, 0x2b, 0xf5,
	0x37, 0x5e, 0xf0, 0xf0, 0x53, 0x78, 0x6c, 0x0c, 0x39, 0xb1, 0x4f, 0x4d, 0xde, 0xe0, 0xec, 0xb7,
	0xd3, 0x5d, 0x84, 0x52, 0x3a, 0x8f, 0x1c, 0x0a, 0x3f, 0xb3, 0x1c, 0x4e, 0xda, 0x46, 0x22, 0x29,
	0xe7, 0x89, 0x43, 0x11, 0xd7, 0xce, 0x91, 0xca, 0xa8, 0xce, 0x49, 0x83, 0xb3, 0x5f, 0x1f, 0xee,
	0xde, 0x67, 0x7f, 0x78, 0xd4, 0x65, 0xcf, 0xaf, 0xb3, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x80,
	0x3d, 0xa4, 0xfb, 0x12, 0x02, 0x00, 0x00,
}
