// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/waylennn/chaincode/adopter/protos/github.com/waylennn/chaincode/adopter/adopter-file-v1.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FileV1 struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Hash                 string   `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Size                 uint64   `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileV1) Reset()         { *m = FileV1{} }
func (m *FileV1) String() string { return proto.CompactTextString(m) }
func (*FileV1) ProtoMessage()    {}
func (*FileV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_1af4b23248e375e7, []int{0}
}

func (m *FileV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileV1.Unmarshal(m, b)
}
func (m *FileV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileV1.Marshal(b, m, deterministic)
}
func (m *FileV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileV1.Merge(m, src)
}
func (m *FileV1) XXX_Size() int {
	return xxx_messageInfo_FileV1.Size(m)
}
func (m *FileV1) XXX_DiscardUnknown() {
	xxx_messageInfo_FileV1.DiscardUnknown(m)
}

var xxx_messageInfo_FileV1 proto.InternalMessageInfo

func (m *FileV1) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FileV1) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *FileV1) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type FilePayloadV1 struct {
	Files                []*FileV1 `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *FilePayloadV1) Reset()         { *m = FilePayloadV1{} }
func (m *FilePayloadV1) String() string { return proto.CompactTextString(m) }
func (*FilePayloadV1) ProtoMessage()    {}
func (*FilePayloadV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_1af4b23248e375e7, []int{1}
}

func (m *FilePayloadV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilePayloadV1.Unmarshal(m, b)
}
func (m *FilePayloadV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilePayloadV1.Marshal(b, m, deterministic)
}
func (m *FilePayloadV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilePayloadV1.Merge(m, src)
}
func (m *FilePayloadV1) XXX_Size() int {
	return xxx_messageInfo_FilePayloadV1.Size(m)
}
func (m *FilePayloadV1) XXX_DiscardUnknown() {
	xxx_messageInfo_FilePayloadV1.DiscardUnknown(m)
}

var xxx_messageInfo_FilePayloadV1 proto.InternalMessageInfo

func (m *FilePayloadV1) GetFiles() []*FileV1 {
	if m != nil {
		return m.Files
	}
	return nil
}

type FileStatV1 struct {
	Logs                 []string `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileStatV1) Reset()         { *m = FileStatV1{} }
func (m *FileStatV1) String() string { return proto.CompactTextString(m) }
func (*FileStatV1) ProtoMessage()    {}
func (*FileStatV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_1af4b23248e375e7, []int{2}
}

func (m *FileStatV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileStatV1.Unmarshal(m, b)
}
func (m *FileStatV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileStatV1.Marshal(b, m, deterministic)
}
func (m *FileStatV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileStatV1.Merge(m, src)
}
func (m *FileStatV1) XXX_Size() int {
	return xxx_messageInfo_FileStatV1.Size(m)
}
func (m *FileStatV1) XXX_DiscardUnknown() {
	xxx_messageInfo_FileStatV1.DiscardUnknown(m)
}

var xxx_messageInfo_FileStatV1 proto.InternalMessageInfo

func (m *FileStatV1) GetLogs() []string {
	if m != nil {
		return m.Logs
	}
	return nil
}

func init() {
	proto.RegisterType((*FileV1)(nil), "adopter.FileV1")
	proto.RegisterType((*FilePayloadV1)(nil), "adopter.FilePayloadV1")
	proto.RegisterType((*FileStatV1)(nil), "adopter.FileStatV1")
}

func init() {
	proto.RegisterFile("github.com/waylennn/chaincode/adopter/protos/github.com/waylennn/chaincode/adopter/adopter-file-v1.proto", fileDescriptor_1af4b23248e375e7)
}

var fileDescriptor_1af4b23248e375e7 = []byte{
	// 216 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xf2, 0x4a, 0xcf, 0x2c, 0xd1,
	0x2b, 0x2c, 0x4d, 0x2d, 0xaa, 0x4c, 0x4e, 0x2c, 0xd0, 0x4b, 0xce, 0xcf, 0xd5, 0x4f, 0xce, 0xc9,
	0x2f, 0x4d, 0x49, 0xce, 0x48, 0xcc, 0xcc, 0xd3, 0x07, 0x93, 0xc9, 0xf9, 0x29, 0xa9, 0xfa, 0x05,
	0x45, 0xf9, 0x25, 0xf9, 0xc5, 0xfa, 0x89, 0x29, 0xf9, 0x05, 0x25, 0xa9, 0x45, 0x30, 0x5a, 0x37,
	0x2d, 0x33, 0x27, 0x55, 0xb7, 0xcc, 0x50, 0x0f, 0x2c, 0x2d, 0xc4, 0x0e, 0x15, 0x56, 0x72, 0xe1,
	0x62, 0x73, 0xcb, 0xcc, 0x49, 0x0d, 0x33, 0x14, 0x12, 0xe2, 0x62, 0xc9, 0x4b, 0xcc, 0x4d, 0x95,
	0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x41, 0x62, 0x19, 0x89, 0xc5, 0x19, 0x12, 0x4c,
	0x10, 0x31, 0x10, 0x1b, 0x24, 0x56, 0x9c, 0x59, 0x95, 0x2a, 0xc1, 0xac, 0xc0, 0xa8, 0xc1, 0x12,
	0x04, 0x66, 0x2b, 0x99, 0x71, 0xf1, 0x82, 0x4c, 0x09, 0x48, 0xac, 0xcc, 0xc9, 0x4f, 0x4c, 0x09,
	0x33, 0x14, 0x52, 0xe5, 0x62, 0x05, 0x59, 0x58, 0x2c, 0xc1, 0xa8, 0xc0, 0xac, 0xc1, 0x6d, 0xc4,
	0xaf, 0x07, 0xb5, 0x4f, 0x0f, 0x62, 0x59, 0x10, 0x44, 0x56, 0x49, 0x81, 0x8b, 0x0b, 0x24, 0x10,
	0x5c, 0x92, 0x58, 0x02, 0x71, 0x41, 0x4e, 0x7e, 0x3a, 0x44, 0x0f, 0x67, 0x10, 0x98, 0xed, 0x64,
	0x16, 0x65, 0x42, 0x8e, 0xb7, 0x93, 0xd8, 0xc0, 0x7c, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xcd, 0x9d, 0x56, 0xc1, 0x35, 0x01, 0x00, 0x00,
}
